name: Pull Request Labeled

on:
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  pull-request-labeled-deprecation-review-complete:
    name: deprecation-review/complete label added
    if: github.event.label.name == 'deprecation-review/complete ✅'
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-token
        env:
          RELEASE_BOARD_GH_APP_CREDS: ${{ secrets.RELEASE_BOARD_GH_APP_CREDS }}
        run: |
          set -eo pipefail
          TOKEN=$(npx @electron/github-app-auth --creds=$RELEASE_BOARD_GH_APP_CREDS --org=electron)
          echo "TOKEN=$TOKEN" >> "$GITHUB_OUTPUT"
      - name: Set status
        if: ${{ steps.generate-token.outputs.TOKEN }}
        uses: dsanders11/update-project-action@7ade91760df70df76770a238abee7a4869e01cf8
        with:
          github_token: ${{ steps.generate-token.outputs.TOKEN }}
          organization: electron
          project_number: 94
          content_id: ${{ github.event.pull_request.node_id }}
          field: Status
          value: ✅ Reviewed
